### PR TITLE
Example multilingual sitemap v1

### PR DESCRIPTION
**Pull request by AIC-BV**
Mix of https://github.com/utopigstudio/octobercms-plugin-seo and https://github.com/mjauvin/wn-mlsitemap-plugin, Perhaps this can help getting started with officialy supporting multilingual sitemaps

### CODE REVIEW

**Comment by mjauvin** [comment]
This is not acceptable for the base plugin, we need to allow EXTENDING its functionality, not incorporate multilang changes in it.

**Comment by LukeTowers** [comment]
@mjauvin can you link this from the other PR for reference?

**Comment by mjauvin** [comment]
@LukeTowers for what purpose exactly ?

**Comment by LukeTowers** [comment]
Just for my own later reference when I review the PR to make sure that it can cover all the use cases

**Comment by AIC-BV** [comment]
> This is not acceptable for the base plugin, we need to allow EXTENDING its functionality, not incorporate multilang changes in it.

Very well aware (as mentioned in Discord)
@LukeTowers asked for a PR to see the code

**Pull request closed without merging**
